version: "3.9"

services:
  database:
    image: postgres:16
    container_name: voa-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backnet



  backend:
    build: ./backend
    container_name: voa-backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
    volumes:
      - ./backend:/app
    depends_on:
      - database
    networks:
      - backnet
      - frontnet




  frontend:
    build: ./frontend
    container_name: voa-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - frontnet

networks:
  frontnet:
    driver: bridge
  backnet:
    driver: bridge

volumes:
  pgdata:
