# Redis configuration file

##########################
# GENERAL SETTINGS
##########################

# Port to listen on
port 6379

# Bind to all network interfaces (needed for Docker)
bind 0.0.0.0

# Protected mode
protected-mode yes

# TCP keepalive
tcp-keepalive 300

# Databases
databases 16

##########################
# SECURITY
##########################

# Require password to access Redis
requirepass 0@192@300@53@3493@3.14

##########################
# MEMORY MANAGEMENT
##########################

# Maximum memory usage
maxmemory 64mb

# Eviction policy when memory limit is reached
maxmemory-policy allkeys-lru