{
 "title": "VOA",
 "time": { "from": "2025-10-25T20:20:17.155Z", "to": "2025-10-25T20:33:05.781Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "ENDPOINTS REQUESTS/MIN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (handler) (\r\n  rate(http_requests_total{handler!~\"/health|/metrics|/docs|/openapi.json\"}[1m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "nginx_up{job=\"nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DATABASE",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "pg_up{job=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMV DB SIZE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{job=\"postgres\", datname=\"SMV\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REDIS MEMORY USED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REDIS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "redis_up{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}