name: CI PIPELINE

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: Install Dependencies
          run: |
            cd backend && pip install --no-cache-dir -r requirements.txt
            pytest -v
