name: CI PIPELINE

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
    core_scan:
      uses: ./.github/workflows/security.yml
      
    unit_tests:
        needs: core_scan
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
      
        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'

        - name: Install Dependencies
          run: |
            cd backend && pip install --no-cache-dir -r requirements.txt

        - name: Install Docker Compose
          run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

        - name: Build and start services
          run: docker-compose -f docker-compose.yml up -d --build
        
        - name: Run backend tests
          run: |
            docker exec voa-backend pytest -v --tb=short
        
        - name: Shutdown services
          run: docker-compose down -v